
language: r
# https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
sudo: false
cache: packages

before_script:
  # install the pkg so it can be used as a vig builder (only necessary for packagedocs)
  - Rscript -e "devtools::install()"

# install locally to avoid rev dep
r_binary_packages:
  # - covr # code coverage check
  - lintr # code lint

r_github_packages:
  - schloerke/travisDrat # deploy to drat


after_success:
  - Rscript -e "packagedocs::deploy_travis()"
  - Rscript -e "travisDrat::deploy_drat()"

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
  - master
  - dev
  - travis
env:
  global:
    secure: "NOVFLZuO7dUzmab2c1lQfua0ibLICLPSCsKcD4WKnEH4xrE8W72GVhsXFTLDEmTjgQnUjoq7uGlMf9VoUo2w0t3VhV683mGFOfYSncg01xiDIUU7lT6LXSAjEBLyOYE/jNr1V2lkIYaGrSvjbEGHSxU3lA1WCzXIZCVcjw+qS1NOnPOpMU1SCKNprq995KrYFTCBLlusMbRnySwM+SWrWJX4o1GcUKCrAKA5BiTqTb/7MndcL80hBlv+898ARFhZqsKkyZWFSWb/yk8Ym7m9XyX+OyUGp+APK62qavo9n8tF6ATywgwubjy0DH4pAovzGMwwVBttp0wUcL+CiFJSv7w9njC5IEQmMbW1tkEFDuD22qEZLg3FA74JkSIhHKevcBW7tcmLjwDNTSd2RuUGJaj0/odszZz1lovtHYl9VQUccJK9y6Az9JmUDrYHWhp3/eshMI6OwlWwuUgCc0paM/mzUQjx9sgf0AyYsgb4XfrZ+OVSK1WDWzoYrTRgG2Ip38ZJH0ZqXq8AOvvkzo8wAjMkUxg6YOK2tZ9Bx6QE8WKYEGVVtjJXqK8yPDroaBH15Siwtd3w40xxdcEMSQfTSvuHMIYsbsjm3/XMO53iFyl5hM4LRq6KDCf8Vv7OnP4dCuI6p688o4ZX/PMxSXeIe06o+2OkedglGR6kmQZWPk4="
