
language: r
# https://blog.rstudio.org/2016/03/09/r-on-travis-ci/
sudo: false
cache: packages
warnings_are_errors: false # until stable

before_script:
  # install the pkg so it can be used as a vig builder
  - Rscript -e "devtools::install()"
  - Rscript -e "packagedocs::packagedocs_init_vignettes()"

# install locally to avoid rev dep
r_github_packages:
  # - jimhester/covr # code coverage check
  - jimhester/lintr # code lint

# after_success:
#   - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
  - master
  - dev
  - travis
env:
  global:
    secure: wsSvojLZ29Oeo1d8SQg82rTaGTmoClgG2tSXCst6JOUOzFOGQL23OCI08YGcVl+85nHb+aKqWgW9HurF1/hY7WxjDZ4AQH58hiNrhZhvru8vcTKE2PLsFLk6+BoEPtTcTNMRej91zxWo+494oOYOP19CfRdp7oDxhxpOLzsjgsFn046iK7GOJww7yicRTCjcemeQmy4KWkjHPjtLFCE2JtTXAFZ1rLDJmwds9bdURDyPt/zUX92i0j3ge4pK7OeGVkw2OTx4WdtR/cC83I72yFtZMYDyRlPBQQjUh1NPFFIyS7cLW7wK3GS5Qe4C9OGE78mvvvP3fkgFuf3iF0rJxue5tpwahUR0p/BDO5Y1h12YIE4rmbVHCtGo/16OXJErGMLqUbL5tk89qMZauYrSdvPJEeB/KXgmF8QejJZTVZlHjkOx7v6UxxgPPe9TCF5RX2uGFuY0RL7Ggw8NZVYJjmnL8w0Ct4lcXvQ6rysAhpv30SPm820SvrP0nbZQyBMpRAd4qynfVkhd4DPw+N67BY03kg/IiH3jLKryDDwwry+BNtwyOzOETMp411koBIu1KRBqp/c44yjeXs70l9Wml1EyFNdfOc7jTWHnISoyBRC856UIoXndHIXRB4vSN1PBNowXBhTdeILRHKGLwFsSEubxLOj3c8wpxDf/E72fvaI=
